"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.getAnimeSearchSuggestion = exports.getAnimeEpisodeSources = exports.getAnimeAboutInfo = exports.getProducerAnimes = exports.getEpisodeServers = exports.getAnimeCategory = exports.getAnimeEpisodes = exports.getHomePageInfo = exports.getAnimeSearch = exports.getGenreAnime = void 0;
const animeGenre_controller_1 = __importDefault(require("./animeGenre.controller"));
exports.getGenreAnime = animeGenre_controller_1.default;
const homePage_controller_1 = __importDefault(require("./homePage.controller"));
exports.getHomePageInfo = homePage_controller_1.default;
const animeSearch_controller_1 = __importDefault(require("./animeSearch.controller"));
exports.getAnimeSearch = animeSearch_controller_1.default;
const animeEpisodes_controller_1 = __importDefault(require("./animeEpisodes.controller"));
exports.getAnimeEpisodes = animeEpisodes_controller_1.default;
const animeCategory_controller_1 = __importDefault(require("./animeCategory.controller"));
exports.getAnimeCategory = animeCategory_controller_1.default;
const animeProducer_controller_1 = __importDefault(require("./animeProducer.controller"));
exports.getProducerAnimes = animeProducer_controller_1.default;
const episodeServers_controller_1 = __importDefault(require("./episodeServers.controller"));
exports.getEpisodeServers = episodeServers_controller_1.default;
const animeAboutInfo_controller_1 = __importDefault(require("./animeAboutInfo.controller"));
exports.getAnimeAboutInfo = animeAboutInfo_controller_1.default;
const animeEpisodeSrcs_controller_1 = __importDefault(require("./animeEpisodeSrcs.controller"));
exports.getAnimeEpisodeSources = animeEpisodeSrcs_controller_1.default;
const animeSearchSuggestion_controller_1 = __importDefault(require("./animeSearchSuggestion.controller"));
exports.getAnimeSearchSuggestion = animeSearchSuggestion_controller_1.default;
