"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.scrapeAnimeSearchSuggestion = exports.scrapeAnimeEpisodeSources = exports.scrapeAnimeAboutInfo = exports.scrapeProducerAnimes = exports.scrapeEpisodeServers = exports.scrapeAnimeCategory = exports.scrapeAnimeEpisodes = exports.scrapeAnimeSearch = exports.scrapeGenreAnime = exports.scrapeHomePage = void 0;
const homePage_1 = __importDefault(require("./homePage"));
exports.scrapeHomePage = homePage_1.default;
const animeGenre_1 = __importDefault(require("./animeGenre"));
exports.scrapeGenreAnime = animeGenre_1.default;
const animeSearch_1 = __importDefault(require("./animeSearch"));
exports.scrapeAnimeSearch = animeSearch_1.default;
const animeEpisodes_1 = __importDefault(require("./animeEpisodes"));
exports.scrapeAnimeEpisodes = animeEpisodes_1.default;
const animeCategory_1 = __importDefault(require("./animeCategory"));
exports.scrapeAnimeCategory = animeCategory_1.default;
const animeProducer_1 = __importDefault(require("./animeProducer"));
exports.scrapeProducerAnimes = animeProducer_1.default;
const episodeServers_1 = __importDefault(require("./episodeServers"));
exports.scrapeEpisodeServers = episodeServers_1.default;
const animeAboutInfo_1 = __importDefault(require("./animeAboutInfo"));
exports.scrapeAnimeAboutInfo = animeAboutInfo_1.default;
const animeEpisodeSrcs_1 = __importDefault(require("./animeEpisodeSrcs"));
exports.scrapeAnimeEpisodeSources = animeEpisodeSrcs_1.default;
const animeSearchSuggestion_1 = __importDefault(require("./animeSearchSuggestion"));
exports.scrapeAnimeSearchSuggestion = animeSearchSuggestion_1.default;
