"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SRC_SEARCH_URL = exports.SRC_HOME_URL = exports.SRC_AJAX_URL = exports.SRC_BASE_URL = exports.ACCEPT_HEADER = exports.USER_AGENT_HEADER = exports.ACCEPT_ENCODING_HEADER = void 0;
exports.ACCEPT_ENCODING_HEADER = "gzip, deflate, br";
exports.USER_AGENT_HEADER = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4692.71 Safari/537.36";
exports.ACCEPT_HEADER = "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9";
exports.SRC_BASE_URL = "https://aniwatch.to";
exports.SRC_AJAX_URL = "https://aniwatch.to/ajax";
exports.SRC_HOME_URL = "https://aniwatch.to/home";
exports.SRC_SEARCH_URL = "https://aniwatch.to/search";
