"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.extractMostPopularAnimes = exports.extractTop10Animes = exports.retrieveServerId = exports.substringBefore = exports.substringAfter = exports.extractAnimes = exports.ACCEPT_ENCODING_HEADER = exports.USER_AGENT_HEADER = exports.SRC_SEARCH_URL = exports.ACCEPT_HEADER = exports.SRC_BASE_URL = exports.SRC_HOME_URL = exports.SRC_AJAX_URL = void 0;
const constants_1 = require("./constants");
Object.defineProperty(exports, "SRC_AJAX_URL", { enumerable: true, get: function () { return constants_1.SRC_AJAX_URL; } });
Object.defineProperty(exports, "SRC_HOME_URL", { enumerable: true, get: function () { return constants_1.SRC_HOME_URL; } });
Object.defineProperty(exports, "SRC_BASE_URL", { enumerable: true, get: function () { return constants_1.SRC_BASE_URL; } });
Object.defineProperty(exports, "ACCEPT_HEADER", { enumerable: true, get: function () { return constants_1.ACCEPT_HEADER; } });
Object.defineProperty(exports, "SRC_SEARCH_URL", { enumerable: true, get: function () { return constants_1.SRC_SEARCH_URL; } });
Object.defineProperty(exports, "USER_AGENT_HEADER", { enumerable: true, get: function () { return constants_1.USER_AGENT_HEADER; } });
Object.defineProperty(exports, "ACCEPT_ENCODING_HEADER", { enumerable: true, get: function () { return constants_1.ACCEPT_ENCODING_HEADER; } });
const methods_1 = require("./methods");
Object.defineProperty(exports, "extractAnimes", { enumerable: true, get: function () { return methods_1.extractAnimes; } });
Object.defineProperty(exports, "substringAfter", { enumerable: true, get: function () { return methods_1.substringAfter; } });
Object.defineProperty(exports, "substringBefore", { enumerable: true, get: function () { return methods_1.substringBefore; } });
Object.defineProperty(exports, "retrieveServerId", { enumerable: true, get: function () { return methods_1.retrieveServerId; } });
Object.defineProperty(exports, "extractTop10Animes", { enumerable: true, get: function () { return methods_1.extractTop10Animes; } });
Object.defineProperty(exports, "extractMostPopularAnimes", { enumerable: true, get: function () { return methods_1.extractMostPopularAnimes; } });
